### ISSUE TITLE
Add support for additional html-to-text config options

### ISSUE THREAD

**Issue by fmmich** [jsreport/jsreport-html-to-text#1]
Currently, the only configuration option for the jsreport-html-to-text recipe is wordwrap.  The [html-to-text dependency](https://github.com/werk85/node-html-to-text) has support for additional options that I need to set, but the recipe seems to ignore the other settings, even if they are provided in the rendering request.  In particular, I have an immediate need to set the following html-to-text options: tables, ignoreHref, ignoreImage, preserveNewLines, uppercaseHeadings, singleNewLineParagraphs.

Please note that I am using Jsreport.Client (.NET) to define the rendering request.  If it expedites the request, I do not immediately need these options present in Jsreport Studio.

**Comment by pofider** [comment]
Thank you for your feature request - it is now implemented in jsreport-html-to-text@1.2

All options are now supported in studio and we also merge the options from all these sources and pass it to the html-to-text  dependency

1. global jsreport configuration set in the `html-to-text` node
2. options stored in studio
3. options passed in the API request\

See the updated docs http://jsreport.net/learn/html-to-text

Please note I renamed `wordWrap` property to `wordwrap` to match the options in the dependency. I didn't rise the major version of this package even I know it is breaking to reserve it for jsreport@2 release. I hope this doesn't bother.

**Comment by pofider** [comment]
I didn't spent too much time with testing all of the options. Please open issues if you find some bugs.
