### ISSUE TITLE
Support for html-to-text 6

### ISSUE THREAD

**Issue by InExtremaRes** [jsreport/jsreport-html-to-text#3]
Hi there. First of all thank you for all your work.

[html-to-text](https://github.com/html-to-text/node-html-to-text) released  [version 6](https://github.com/html-to-text/node-html-to-text/blob/master/CHANGELOG.md#version-600) recently. It has better support for whitespaces and block-level tags, something I've missing long time. There is also better support for tables and new options (like `tags`).

It would be nice if you can update this package to support those new features.

**Comment by pofider** [comment]
I am glad you like what we do.

I've just release jsreport-html-to-text@2.2.0 which includes html-to-text@6.0.0

**Comment by InExtremaRes** [comment]
Thank you @pofider for your quick response and action!

I'm testing it and although it works some options are not updated. For instance you can see [here](https://github.com/html-to-text/node-html-to-text#general-options) that `tables` allows `true` but here https://github.com/jsreport/jsreport-html-to-text/blob/22c39dc162b647f689ded0d50c93b2f8ad1e8285/lib/main.js#L31-L33 it forces the option to be an array; also the schema of this extension only allows `string`, passing an array throws with the message

```plain
Error: template input in request contain values that does not match the defined schema. schema validation errors: template.htmlToText.tables should be string
```

Other options, like `tags` or `limits`, works even if they aren't listed with `reporter.documentStore.registerComplexType`.

**Comment by pofider** [comment]
I pushed to git some changes that include `tablesSelectAll` option.
You can get it using `npm i jsreport/jsreport-html-to-text`.

Does this cover your needs? Do you need some additional props?
Feel free to send PR or let me know.

The new options for tags will need some extra work to cover it right in the future.

**Comment by InExtremaRes** [comment]
@pofider Thank you very much. It works.

It covers my neesd but I'm curious: Is there a reason to create another option instead of reuse `tables`? 

As I said before, I can use the `tag` option with no issues (AFAICT) though the API, I've never used this recipe with the studio. Is it accidental that it works?

I would be happy to send a PR but I don't know the architecture at all :( However this changes are what I wanted, the other options are just a "nice to have".

**Comment by pofider** [comment]
> It covers my neesd but I'm curious: Is there a reason to create another option instead of reuse tables?

The reason is that we persist these options in the templates store.
The templates store have also SQL drivers with exact schema and you can't put boolean and string into one column.

> As I said before, I can use the tag option with no issues (AFAICT) though the API, I've never used this recipe with the studio. Is it accidental that it works?

In-studio you won't be able to fill the tags because there is no UI for it and also when the entity definition doesn't include this, you won't be able to persist such entity. You can use the API for now because we take everything we receive.

I created an extra issue to add support for more options to the backlog
https://github.com/jsreport/jsreport-html-to-text/issues/4

**Comment by InExtremaRes** [comment]
I understand. Thank you for the explanation. I think this resolves my current use cases.
